services:
  postgres:
    image: postgres:18.1
    container_name: mamirri-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mamirri}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
